# Generated by Django 4.0 on 2022-01-02 17:11

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('plate', models.IntegerField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname_fa', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname_en', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms')], max_length=16)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile_1', models.CharField(blank=True, max_length=32, null=True)),
                ('mobile_2', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.URLField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator])),
                ('national_code', models.CharField(blank=True, max_length=32, null=True)),
                ('comment', models.TextField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=128, null=True)),
                ('name_en', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator])),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('economic_code', models.CharField(blank=True, max_length=16, null=True)),
                ('national_id', models.CharField(blank=True, max_length=16, null=True)),
                ('workshop_code', models.CharField(blank=True, max_length=16, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=16, null=True)),
                ('contact', models.ManyToManyField(blank=True, null=True, to='contacts.Contact', verbose_name='Employee(s)')),
            ],
        ),
    ]
