# Generated by Django 4.0 on 2022-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, to='contacts.Contact', verbose_name='Employee(s)'),
        ),
    ]
