# Generated by Django 4.0 on 2021-12-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
    ]
