# Generated by Django 4.0 on 2022-01-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastname_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname_fa',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_fa',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
