# Generated by Django 4.0 on 2022-01-01 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_lastname_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms')], default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
    ]
