# Generated by Django 4.0 on 2022-02-01 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_hashtag_company_hashtag_contact_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='Seperate emails with comma', max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Seperate emails with comma', max_length=254, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(help_text='This Field Should be English', max_length=128, unique=True),
        ),
    ]
