# Generated by Django 4.0 on 2022-01-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='gender',
        ),
    ]
