# Generated by Django 4.0 on 2022-01-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms')], default=False, max_length=16),
        ),
    ]
