# Generated by Django 4.0 on 2022-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_mobile_1_contact_mobile_2_contact_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
