# Generated by Django 4.0 on 2022-02-02 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_alter_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(upload_to='contact', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
