# Generated by Django 4.0 on 2022-01-01 16:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(default=('IR', 'iran'), max_length=2),
        ),
    ]
