# Generated by Django 4.0 on 2022-01-01 16:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=('IR', 'iran'), max_length=2, null=True),
        ),
    ]
