# Generated by Django 4.0 on 2022-02-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_alter_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
