# Generated by Django 4.0 on 2022-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_alter_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
