# Generated by Django 4.0 on 2022-02-04 15:26

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_remove_contact_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت ها'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطب ها'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='address',
            name='plate',
            field=models.IntegerField(blank=True, null=True, verbose_name='پلاک'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=256, verbose_name='نام آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('private', 'آدرس خصوصی یا شخصی'), ('invoice', 'آدرس فاکتور'), ('delivery ', 'آدرس ارسال یا دریافت'), ('other', 'دیگر آدرس ها ')], default=('delivery ', 'Delivery Address'), max_length=128, verbose_name='نوع آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, to='contacts.Contact', verbose_name='کارمند (ها)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='economic_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره اقتصادی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل ها را با کاما از هم جدا کنید', max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='ایمیل (ها)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='hashtag',
            field=models.ManyToManyField(to='contacts.Hashtag', verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام شرکت به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_fa',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام شرکت به فارسی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='national_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره ثبت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator], verbose_name='وب سایت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='workshop_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='کد کارگاه'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل ها را با کاما جدا کنید', max_length=254, null=True, validators=[django.core.validators.EmailValidator], verbose_name='ایمیل (ها)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('mr', 'آقا'), ('ms', 'خانم')], max_length=16, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hashtag',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Hashtag', verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='نام خانوادگی به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname_fa',
            field=models.CharField(max_length=64, verbose_name='نام خانوادگی به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_1',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='موبایل 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='موبایل 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='نام به انگلیسی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name_fa',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='نام به فارسی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='national_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True, validators=[django.core.validators.URLValidator], verbose_name='وب سایت'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='نام برچسب'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(help_text='به انگلیسی باشد، به جای اسپیس از خط تیره استفاده کنید، هر چه کوتاه تر بهتر و با نام برچسب مرتبط باشد', max_length=128, unique=True, verbose_name='اسلاگ'),
        ),
    ]
