# Generated by Django 4.0 on 2022-02-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_address_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='hashtag',
            field=models.ManyToManyField(to='contacts.Hashtag', verbose_name='برچسب'),
        ),
    ]
