# Generated by Django 4.0 on 2022-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_alter_contact_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
