# Generated by Django 4.0 on 2022-01-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_alter_contact_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[(False, 'Select Gender'), ('mr', 'Mr'), ('ms', 'Ms')], max_length=16),
        ),
    ]
