# Generated by Django 4.0 on 2022-01-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_alter_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('mr', 'Mr'), ('ms', 'Ms')], max_length=16),
        ),
    ]
