# Generated by Django 4.0 on 2022-02-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_alter_company_hashtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'مخاطب', 'verbose_name_plural': 'مخاطب'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب'},
        ),
        migrations.AlterField(
            model_name='company',
            name='hashtag',
            field=models.ManyToManyField(to='contacts.Hashtag', verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hashtag',
            field=models.ManyToManyField(to='contacts.Hashtag', verbose_name='برچسب'),
        ),
    ]
