# Generated by Django 4.0 on 2022-01-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_alter_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='national_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
