# Generated by Django 4.0 on 2022-01-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_contact_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
