# Generated by Django 4.0 on 2022-02-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_alter_contact_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='contacts.Hashtag', verbose_name='برچسب'),
        ),
    ]
