# Generated by Django 4.0 on 2022-01-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_contact_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128)),
            ],
        ),
    ]
