# Generated by Django 4.0 on 2022-01-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
