# Generated by Django 4.0 on 2022-01-01 18:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_company_address_company_city_company_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('province', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('plate', models.IntegerField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='company',
            name='province',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='province',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zipcode',
        ),
    ]
