# Generated by Django 4.0 on 2022-01-01 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_address_remove_company_address_remove_company_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
