# Generated by Django 4.0 on 2022-01-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0032_alter_company_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Contact'),
        ),
    ]
