# Generated by Django 4.0 on 2022-01-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0033_remove_company_contact_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
