# Generated by Django 4.0 on 2022-01-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_alter_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Contact'),
        ),
    ]
