# Generated by Django 4.0 on 2022-01-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0035_alter_company_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='economic_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='national_id',
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='workshop_code',
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Contact', verbose_name='Employee(s)'),
        ),
    ]
