# Generated by Django 4.0 on 2022-01-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0036_company_economic_code_company_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='workshop_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
