# Generated by Django 4.0 on 2022-01-01 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0037_alter_company_workshop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='economic_code',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.DecimalValidator]),
        ),
        migrations.AlterField(
            model_name='company',
            name='national_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='workshop_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
