# Generated by Django 4.0 on 2022-01-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_alter_company_economic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='economic_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='national_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='workshop_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
