# Generated by Django 4.0 on 2022-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0040_alter_company_economic_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
