# Generated by Django 4.0 on 2022-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
