# Generated by Django 4.0 on 2022-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
