# Generated by Django 4.0 on 2022-02-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_invoice_is_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
