# Generated by Django 4.0 on 2022-02-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_address_options_alter_company_options_and_more'),
        ('sell', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(default='', max_length=2048, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='مخاطب'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده؟'),
        ),
    ]
