# Generated by Django 4.0 on 2022-02-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_address_options_alter_company_options_and_more'),
        ('sell', '0005_post_alter_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.invoice')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.satellite')),
            ],
        ),
    ]
