# Generated by Django 4.0 on 2022-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_invoice_description_alter_invoice_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='توضیحات'),
        ),
    ]
