# Generated by Django 4.0 on 2022-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_invoice_satellite_invoiceitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Satellite',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.CharField(default=0, max_length=32, verbose_name='مبلغ'),
            preserve_default=False,
        ),
    ]
