# Generated by Django 4.0 on 2022-02-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_invoice_is_cancel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'پیش فاکتور', 'verbose_name_plural': 'پیش فاکتور'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'آیتم های فاکتور', 'verbose_name_plural': 'آیتم های فاکتور'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_payed',
        ),
    ]
