# Generated by Django 4.0 on 2022-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Km', 'km'), ('Mile', 'mile')], default=0, max_length=128),
            preserve_default=False,
        ),
    ]
