# Generated by Django 4.0 on 2022-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=128),
        ),
    ]
