# Generated by Django 4.0 on 2022-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('Km', 'km'), ('Mile', 'mile')], default=('Km', 'km'), max_length=128),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
