# Generated by Django 4.0 on 2022-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_remove_invoiceitem_price_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
