# Generated by Django 4.0 on 2022-02-21 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_remove_product_unit_invoiceitem_unit_delete_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=0, verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
