# Generated by Django 4.0 on 2022-02-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_invoice_date_invoiceitem_created_invoiceitem_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
