# Generated by Django 4.0 on 2022-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_product_slug_alter_invoiceitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
