# Generated by Django 4.0 on 2022-02-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_remove_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='created',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='updated',
        ),
    ]
