# Generated by Django 4.0 on 2022-02-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
