# Generated by Django 4.0 on 2022-02-21 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_remove_invoiceitem_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
    ]
