# Generated by Django 4.0 on 2022-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
