# Generated by Django 4.0 on 2022-02-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0014_alter_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(max_length=128, verbose_name='مقدار'),
        ),
    ]
