# Generated by Django 4.0 on 2022-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0018_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
    ]
