# Generated by Django 4.0 on 2022-02-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0019_invoice_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='به درصد', null=True, verbose_name='تخفیف'),
        ),
    ]
