# Generated by Django 4.0 on 2022-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0020_remove_invoice_discount_invoiceitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(default=0, max_length=128, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
