# Generated by Django 4.0 on 2022-02-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0021_invoiceitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default=0, max_length=128, verbose_name='واحد'),
            preserve_default=False,
        ),
    ]
