# Generated by Django 4.0 on 2022-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0025_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
