# Generated by Django 4.0 on 2022-02-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0009_alter_company_hashtag_alter_contact_hashtag'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(help_text='This Field Should be English', max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('send_with', models.CharField(blank=True, choices=[('email', 'Email'), ('fax', 'Fax'), ('post', 'Post'), ('delivery', 'Delivery'), ('physical', 'Physical')], default=[('delivery', 'Delivery')], max_length=32, null=True)),
                ('type', models.CharField(blank=True, choices=[('virtual', 'Virtual'), ('physical', 'Physical')], default=[('delivery', 'Delivery')], max_length=32, null=True)),
                ('hashtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.hashtag')),
                ('to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
                ('to_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
