# Generated by Django 4.0 on 2022-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='content',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
