# Generated by Django 4.0 on 2022-02-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_remove_letter_hashtag_letter_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='subject',
            field=models.CharField(default=False, max_length=512),
            preserve_default=False,
        ),
    ]
