# Generated by Django 4.0 on 2022-02-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_letter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='hashtag',
            field=models.ManyToManyField(to='office.Hashtag'),
        ),
    ]
