# Generated by Django 4.0 on 2022-02-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_alter_letter_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='send_with',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('fax', 'Fax'), ('post', 'Post'), ('delivery', 'Delivery'), ('physical', 'Physical')], default=('delivery', 'Delivery'), max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='type',
            field=models.CharField(blank=True, choices=[('virtual', 'Virtual'), ('physical', 'Physical')], default=('physical', 'Physical'), max_length=32, null=True),
        ),
    ]
