# Generated by Django 4.0 on 2022-02-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_letter_send_with_alter_letter_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='content_new',
            new_name='content',
        ),
        migrations.AddField(
            model_name='letter',
            name='number',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='send_with',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('fax', 'Fax'), ('post', 'Post'), ('delivery', 'Delivery'), ('employer', 'Employer')], default=('delivery', 'Delivery'), max_length=32, null=True),
        ),
    ]
