# Generated by Django 4.0 on 2022-02-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0013_alter_letter_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='')),
                ('lastname_fa', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='')),
                ('name_en', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='')),
                ('lastname_en', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='')),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
