# Generated by Django 4.0 on 2022-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_employer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'کارمند', 'verbose_name_plural': 'کارمند'},
        ),
        migrations.AlterField(
            model_name='employer',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='lastname_en',
            field=models.CharField(default='', max_length=64, verbose_name='نام خانوادگی به انگلیسی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='lastname_fa',
            field=models.CharField(max_length=64, null=True, verbose_name='نام خانوادگی به فارسی'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name_en',
            field=models.CharField(default='', max_length=64, verbose_name='نام به انگلیسی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='name_fa',
            field=models.CharField(default='', max_length=64, verbose_name='نام به فارسی'),
            preserve_default=False,
        ),
    ]
