# Generated by Django 4.0 on 2022-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_alter_employer_options_alter_employer_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='national_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='lastname_fa',
            field=models.CharField(default='', max_length=64, verbose_name='نام خانوادگی به فارسی'),
            preserve_default=False,
        ),
    ]
