# Generated by Django 4.0 on 2022-02-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_alter_letter_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-lastname_fa'], 'verbose_name': 'کارمند', 'verbose_name_plural': 'کارمند'},
        ),
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('national_code',)},
        ),
    ]
