# Generated by Django 4.0 on 2022-02-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
