# Generated by Django 4.0 on 2022-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_employer_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='partner',
            field=models.BooleanField(default=False, verbose_name='شریک است؟'),
        ),
    ]
