# Generated by Django 4.0 on 2022-01-06 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('bank', models.CharField(max_length=256)),
                ('card', models.CharField(max_length=256)),
                ('shomare_hesab', models.CharField(max_length=256)),
                ('shaba', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='pay',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='date_of_payment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='invoice',
            field=models.CharField(choices=[('no_invoice', 'No Invoice'), ('invoice', 'Invoice'), ('official_invoice', 'Official Invoice')], default=('no_invoice', 'No Invoice'), max_length=64),
        ),
        migrations.AddField(
            model_name='pay',
            name='payer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='pay',
            name='to',
            field=models.CharField(help_text='Like Seven Host or Korosh Walmart', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.IntegerField(help_text='It should be in Rial'),
        ),
    ]
