# Generated by Django 4.0 on 2022-01-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='to',
            field=models.CharField(help_text='7host or Korosh Walmart', max_length=256, null=True),
        ),
    ]
