# Generated by Django 4.0 on 2022-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
