# Generated by Django 4.0 on 2022-01-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_company_options'),
        ('accounting', '0002_bankaccount_is_official'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Received',
            new_name='Income',
        ),
    ]
