# Generated by Django 4.0 on 2022-01-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_pay_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='to',
            field=models.CharField(help_text='Like Seven Host or Korosh Walmart', max_length=256, null=True),
        ),
    ]
