# Generated by Django 4.0 on 2022-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_pay_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='card',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='shomare_hesab',
            new_name='card_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
