# Generated by Django 4.0 on 2022-01-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_pay_fee_alter_pay_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
