# Generated by Django 4.0 on 2022-01-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounting', '0003_rename_received_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officialinvoices',
            old_name='company',
            new_name='from_company',
        ),
        migrations.RenameField(
            model_name='officialinvoices',
            old_name='contact',
            new_name='from_contact',
        ),
        migrations.AddField(
            model_name='officialinvoices',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
