# Generated by Django 4.0 on 2022-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_pay_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='invoice',
            field=models.CharField(choices=[('no_invoice', 'No Invoice'), ('invoice', 'Invoice'), ('official_invoice', 'Official Invoice')], default=('no_invoice', 'No Invoice'), max_length=64),
        ),
    ]
