# Generated by Django 4.0 on 2022-01-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_rename_from_company_officialinvoices_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='from_user',
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=32)),
                ('price_currency', models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32)),
                ('comment', models.TextField(blank=True, null=True)),
                ('to_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount')),
            ],
        ),
    ]
