# Generated by Django 4.0 on 2022-01-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounting', '0006_remove_income_from_user_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='title',
        ),
        migrations.AddField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
