# Generated by Django 4.0 on 2022-01-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounting', '0006_pay_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
