# Generated by Django 4.0 on 2022-01-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_pay_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='date_of_payment',
            field=models.DateField(auto_now=True),
        ),
    ]
