# Generated by Django 4.0 on 2022-01-06 13:50

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_pay_balance_currency_pay_ _alter_pay_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name=' ',
        ),
        migrations.AddField(
            model_name='pay',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'EUR €'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pay',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=14, null=True),
        ),
    ]
