# Generated by Django 4.0 on 2022-01-06 13:53

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_pay_ _pay_balance_currency_alter_pay_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='balance_currency',
        ),
        migrations.AddField(
            model_name='pay',
            name='fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='pay',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=14),
        ),
    ]
