# Generated by Django 4.0 on 2022-01-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_pay_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True),
        ),
    ]
