# Generated by Django 4.0 on 2022-01-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_company_email'),
        ('accounting', '0008_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='to',
        ),
        migrations.AddField(
            model_name='sell',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company'),
        ),
        migrations.AddField(
            model_name='sell',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
