# Generated by Django 4.0 on 2022-02-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_sell_to_sell_to_company_sell_to_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
