# Generated by Django 4.0 on 2022-01-06 14:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_remove_pay_balance_remove_pay_balance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='IRR', max_digits=14, null=True),
        ),
    ]
