# Generated by Django 4.0 on 2022-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_pay_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=False, max_length=128),
            preserve_default=False,
        ),
    ]
