# Generated by Django 4.0 on 2022-02-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contacts', '0017_alter_address_options_alter_company_options_and_more'),
        ('accounting', '0011_pay_attach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'حساب بانکی', 'verbose_name_plural': 'حساب های بانکی'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'سرمایه', 'verbose_name_plural': 'سرمایه ها'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'دریافت', 'verbose_name_plural': 'دریافتی ها'},
        ),
        migrations.AlterModelOptions(
            name='officialinvoices',
            options={'verbose_name': 'فاکتور رسمی', 'verbose_name_plural': 'فاکتور ها رسمی'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت ها'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'تنخواه', 'verbose_name_plural': 'تنخواه ها'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=256, unique=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(max_length=256, verbose_name='نام بانک'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(max_length=256, unique=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='حساب رسمی است؟'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='shaba',
            field=models.CharField(max_length=256, unique=True, verbose_name='شبا'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='title',
            field=models.CharField(max_length=256, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='به انگلیسی باشد، هر چه کوتاه تر بهتر، به جای اسپیس از خط تیره استفاده کنید', max_length=128, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='price',
            field=models.CharField(max_length=32, verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد پول هزینه'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='to_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='به حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(default=False, help_text='کارمندی را انتخاب کنید که در شرکت شریک است', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='شریک'),
        ),
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='income',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='income',
            name='from_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='شخص'),
        ),
        migrations.AlterField(
            model_name='income',
            name='price',
            field=models.CharField(max_length=32, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='income',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد پول دریافتی'),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(max_length=256, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='income',
            name='to_bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='به حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact', verbose_name='شخص'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='date_of_invoice',
            field=models.DateField(verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='employer_signature',
            field=models.BooleanField(default=False, verbose_name='امضای کارفرما دارد؟'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='location',
            field=models.CharField(choices=[('company_office', 'شرکت'), ('employer_office', 'شرکت کارفرما')], default=('company_office', 'Company Office'), max_length=64, verbose_name='مکان فاکتور'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='serial_number',
            field=models.CharField(max_length=32, verbose_name='شماره سریال فاکتور'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='status',
            field=models.CharField(choices=[('current', 'جاری'), ('invalid', 'باطل'), ('lost', 'گمشده')], default=('current', 'Current'), max_length=64, verbose_name='وضعیت فاکتور'),
        ),
        migrations.AlterField(
            model_name='officialinvoices',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='موضوع فاکتور'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='account',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='pay', verbose_name='پیوست'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='date_of_payment',
            field=models.DateField(verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fe_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد پول کارمزد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='invoice',
            field=models.CharField(choices=[('no_invoice', 'بدون فاکتور'), ('invoice', 'فاکتور دارد'), ('official_invoice', 'فاکتور رسمی')], default=('no_invoice', 'No Invoice'), max_length=64, verbose_name='وضعیت فاکتور'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.IntegerField(verbose_name='مقدار هزینه'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='source',
            field=models.CharField(choices=[('employer', 'کارمند'), ('company', 'شرکت')], default=('employer', 'کارمند'), help_text='it means you spend money form your pocket or the company', max_length=32, verbose_name='منبع پرداخت'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد پول مالیات'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='title',
            field=models.CharField(max_length=256, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='to',
            field=models.CharField(help_text='Like Seven Host or Korosh Walmart', max_length=256, null=True, verbose_name='به حساب'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='از حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_of_payment',
            field=models.DateField(verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='price',
            field=models.CharField(max_length=32, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد پول مبلغ'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='to',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='به حساب کارمند'),
        ),
    ]
