# Generated by Django 4.0 on 2022-01-06 14:46

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='taxation',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='IRR', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='taxation_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
    ]
