# Generated by Django 4.0 on 2022-02-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_bankaccount_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'سرمایه', 'verbose_name_plural': 'سرمایه'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'دریافت', 'verbose_name_plural': 'دریافتی'},
        ),
        migrations.AlterModelOptions(
            name='officialinvoices',
            options={'verbose_name': 'فاکتور رسمی', 'verbose_name_plural': 'فاکتور های رسمی'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت'},
        ),
    ]
