# Generated by Django 4.0 on 2022-01-06 16:39

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_company_options'),
        ('accounting', '0014_pay_created_pay_updated_alter_pay_taxation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=14)),
                ('comment', models.TextField(blank=True, null=True)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company')),
                ('from_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
        ),
    ]
