# Generated by Django 4.0 on 2022-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_pay_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date_of_payment',
            field=models.DateField(verbose_name='تاریخ پرداخت'),
        ),
    ]
