# Generated by Django 4.0 on 2022-02-09 20:50

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_pay_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date_of_payment',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
