# Generated by Django 4.0 on 2022-01-06 18:38

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_received_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR '), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR '), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR '), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='received',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR '), ('USD', 'USD $')], default='IRR', editable=False, max_length=3),
        ),
    ]
