# Generated by Django 4.0 on 2022-02-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0007_invoice_is_cancel'),
        ('accounting', '0017_alter_pay_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.invoice', verbose_name='بابت فاکتور'),
        ),
    ]
