# Generated by Django 4.0 on 2022-01-11 16:22

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounting', '0019_officialinvoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('IRR', 'IRR '), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IRR', max_digits=14)),
                ('date_of_payment', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount')),
                ('payer', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
