# Generated by Django 4.0 on 2022-02-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounting', '0020_alter_fund_user_alter_pay_payer_alter_salary_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='user',
            field=models.ForeignKey(default=False, help_text='کارمندی را انتخاب کنید که در شرکت شریک است', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='شریک'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='to',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='به حساب کارمند'),
        ),
    ]
