# Generated by Django 4.0 on 2022-01-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='payer',
            new_name='to',
        ),
    ]
