# Generated by Django 4.0 on 2022-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_rename_payer_salary_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
