# Generated by Django 4.0 on 2022-02-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_fund_user_alter_pay_payer_alter_salary_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='payer',
        ),
    ]
