# Generated by Django 4.0 on 2022-01-12 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_salary_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialinvoices',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialinvoices',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
