# Generated by Django 4.0 on 2022-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_officialinvoices_created_officialinvoices_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32),
        ),
    ]
