# Generated by Django 4.0 on 2022-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_pay_payer_alter_fund_user_alter_salary_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='source',
            field=models.CharField(choices=[('employer', 'کارمند'), ('company', 'شرکت')], default=('employer', 'کارمند'), help_text='پرداخت کننده از جیب خودش خرج کرده یا حساب شرکت؟', max_length=32, verbose_name='منبع پرداخت'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='to',
            field=models.CharField(help_text='مانند افق کوروش یا اسنپ باکس', max_length=256, null=True, verbose_name='به حساب'),
        ),
    ]
