# Generated by Django 4.0 on 2022-01-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_pay_price_alter_pay_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='fe_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32),
        ),
    ]
