# Generated by Django 4.0 on 2022-02-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_rename_from_company_income_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='fe_currency',
            new_name='fee_currency',
        ),
        migrations.AlterField(
            model_name='pay',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32, verbose_name='واحد هزینه'),
        ),
    ]
