# Generated by Django 4.0 on 2022-02-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_rename_fe_currency_pay_fee_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='account',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='از حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=models.BigIntegerField(blank=True, max_length=32, null=True, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.BigIntegerField(verbose_name='مقدار هزینه'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation',
            field=models.BigIntegerField(blank=True, max_length=32, null=True, verbose_name='مالیات'),
        ),
    ]
