# Generated by Django 4.0 on 2022-01-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_rename_fe_currency_pay_feee_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='feee_currency',
            new_name='fe_currency',
        ),
    ]
