# Generated by Django 4.0 on 2022-01-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_rename_feee_currency_pay_fe_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='fee_currency',
        ),
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
