# Generated by Django 4.0 on 2022-02-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_pay_account_alter_pay_fee_alter_pay_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='date_of_payment',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='کارمزد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مالیات'),
        ),
    ]
