# Generated by Django 4.0 on 2022-01-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_remove_pay_fee_currency_alter_pay_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='taxation_currency',
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
