# Generated by Django 4.0 on 2022-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_rename_date_of_payment_pay_date_alter_pay_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='shaba',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='شبا'),
        ),
    ]
