# Generated by Django 4.0 on 2022-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='price',
            field=models.BigIntegerField(verbose_name='مبلغ'),
        ),
    ]
