# Generated by Django 4.0 on 2022-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_remove_pay_taxation_currency_alter_pay_taxation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='fee',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
