# Generated by Django 4.0 on 2022-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_salary_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'US Dollar')], default=('IRR', 'ریال'), max_length=32, verbose_name='واحد پول هزینه'),
        ),
        migrations.AlterField(
            model_name='income',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'US Dollar')], default=('IRR', 'ریال'), max_length=32, verbose_name='واحد پول دریافتی'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='fee_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'US Dollar')], default=('IRR', 'ریال'), max_length=32, verbose_name='واحد پول کارمزد'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'US Dollar')], default=('IRR', 'ریال'), max_length=32, verbose_name='واحد هزینه'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='taxation_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'US Dollar')], default=('IRR', 'ریال'), max_length=32, verbose_name='واحد پول مالیات'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'ریال'), ('USD', 'US Dollar')], default=('IRR', 'ریال'), max_length=32, verbose_name='واحد پول مبلغ'),
        ),
    ]
