# Generated by Django 4.0 on 2022-01-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_pay_fee_alter_pay_taxation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='received',
            name='price',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='salary',
            name='price',
            field=models.CharField(max_length=32),
        ),
    ]
