# Generated by Django 4.0 on 2022-01-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_remove_received_price_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='bank_account',
            new_name='to_bank_account',
        ),
    ]
