# Generated by Django 4.0 on 2022-02-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_alter_fund_price_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='date_of_payment',
            new_name='date',
        ),
    ]
