# Generated by Django 4.0 on 2022-02-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_rename_date_of_payment_salary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='to_bank_account',
            new_name='account',
        ),
    ]
