# Generated by Django 4.0 on 2022-01-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_rename_bank_account_salary_to_bank_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received',
            old_name='bank_account',
            new_name='to_bank_account',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='to_bank_account',
            new_name='bank_account',
        ),
    ]
