# Generated by Django 4.0 on 2022-02-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_rename_to_bank_account_income_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='price',
            field=models.BigIntegerField(verbose_name='هزینه'),
        ),
    ]
