# Generated by Django 4.0 on 2022-01-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_rename_bank_account_received_to_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='source',
            field=models.CharField(blank=True, choices=[('employer', 'Employer'), ('company', 'Company')], default=('employer', 'Employer'), max_length=32),
        ),
    ]
