# Generated by Django 4.0 on 2022-01-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_pay_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='account',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount'),
        ),
    ]
