# Generated by Django 4.0 on 2022-01-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_alter_pay_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='source',
            field=models.CharField(choices=[('employer', 'Employer'), ('company', 'Company')], default=('employer', 'Employer'), max_length=32),
        ),
    ]
