# Generated by Django 4.0 on 2022-03-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_rename_to_bank_account_fund_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ پرداخت'),
        ),
    ]
