# Generated by Django 4.0 on 2022-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='date',
            field=models.DateField(default=0, verbose_name='تاریخ'),
            preserve_default=False,
        ),
    ]
