# Generated by Django 4.0 on 2022-01-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_pay_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='taxation_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32),
        ),
    ]
