# Generated by Django 4.0 on 2022-03-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_fund_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='date',
        ),
    ]
