# Generated by Django 4.0 on 2022-01-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_alter_salary_options_salary_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='price_currency',
            field=models.CharField(blank=True, choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('IRR', 'Rial'), max_length=32),
        ),
    ]
