# Generated by Django 4.0 on 2022-01-18 16:20

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_received_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
