# Generated by Django 4.0 on 2022-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_remove_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='price',
            field=models.IntegerField(),
        ),
    ]
